export const SEED_FRIENDS = [
  { id: "f1", name: "Jordan",   initial: "J", totalXP: 4280, archetype: "scholar",  weeklyXP: 540, streak: 12,
    categoryXP: { fitness: 300, school: 2800, life: 180, work: 400, mind: 600 },
    recentActivity: { task: "Read 30 pages",          category: "school",  xp: 65,  minutesAgo: 22  },
    mainQuestToday: { task: "Finish chapter outline", category: "school",  xp: 90,  status: "pending" },
    weeklyQuest:    { task: "Write 5,000 words",      category: "school",  xp: 320, daysLeft: 4, status: "pending" } },
  { id: "f2", name: "Sasha",    initial: "S", totalXP: 6720, archetype: "warrior",  weeklyXP: 820, streak: 22,
    categoryXP: { fitness: 4800, school: 170, life: 800, work: 350, mind: 600 },
    recentActivity: { task: "Morning run · 5K",       category: "fitness", xp: 102, minutesAgo: 45  },
    mainQuestToday: { task: "Lift heavy + mobility",  category: "fitness", xp: 120, status: "complete" },
    weeklyQuest:    { task: "Run 25K total this week", category: "fitness", xp: 380, daysLeft: 2, status: "pending" } },
  { id: "f3", name: "Marcus",   initial: "M", totalXP: 2940, archetype: "monk",     weeklyXP: 380, streak: 4,
    categoryXP: { fitness: 130, school: 350, life: 600, work: 60, mind: 1800 },
    recentActivity: { task: "20 min meditation",      category: "mind",    xp: 38,  minutesAgo: 180 },
    mainQuestToday: { task: "Journal morning pages",  category: "mind",    xp: 60,  status: "pending" },
    weeklyQuest:    { task: "Meditate 7 days straight", category: "mind",  xp: 280, daysLeft: 5, status: "pending" } },
  { id: "f4", name: "Riley",    initial: "R", totalXP: 5180, archetype: "artisan",  weeklyXP: 660, streak: 8,
    categoryXP: { fitness: 280, school: 700, life: 150, work: 3600, mind: 450 },
    recentActivity: { task: "Shipped portfolio update", category: "work",  xp: 145, minutesAgo: 320 },
    mainQuestToday: { task: "Finish client deck",     category: "work",    xp: 130, status: "pending" },
    weeklyQuest:    { task: "Launch portfolio site",  category: "work",    xp: 420, daysLeft: 3, status: "pending" } },
  { id: "f5", name: "Ava",      initial: "A", totalXP: 3850, archetype: "vitalist", weeklyXP: 470, streak: 15,
    categoryXP: { fitness: 650, school: 200, life: 2500, work: 120, mind: 380 },
    recentActivity: { task: "Cooked a real dinner",   category: "life",    xp: 42,  minutesAgo: 90  },
    mainQuestToday: { task: "Call mom + walk park",   category: "life",    xp: 75,  status: "pending" },
    weeklyQuest:    { task: "Cook 5 home meals",      category: "life",    xp: 260, daysLeft: 6, status: "pending" } },
];

export const DISCOVERABLE_USERS = [
  { id: "d1", name: "Kai",   username: "kairuns",     initial: "K", totalXP: 8210, archetype: "warrior",  weeklyXP: 920, streak: 31,
    categoryXP: { fitness: 6200, school: 200, life: 700, work: 400, mind: 710 },
    recentActivity: { task: "12K trail run",             category: "fitness", xp: 168, minutesAgo: 12  },
    mainQuestToday: { task: "Hill sprints",              category: "fitness", xp: 140, status: "pending" },
    weeklyQuest:    { task: "Run 50K this week",         category: "fitness", xp: 480, daysLeft: 2, status: "pending" } },
  { id: "d2", name: "Mira",  username: "mirastudies",  initial: "M", totalXP: 5640, archetype: "scholar",  weeklyXP: 720, streak: 18,
    categoryXP: { fitness: 250, school: 3900, life: 300, work: 680, mind: 510 },
    recentActivity: { task: "Finished thesis chapter",   category: "school",  xp: 145, minutesAgo: 38  },
    mainQuestToday: { task: "Review committee notes",    category: "school",  xp: 110, status: "pending" },
    weeklyQuest:    { task: "Defend chapter draft",      category: "school",  xp: 400, daysLeft: 4, status: "pending" } },
  { id: "d3", name: "Theo",  username: "theozen",      initial: "T", totalXP: 3120, archetype: "monk",     weeklyXP: 410, streak: 6,
    categoryXP: { fitness: 180, school: 420, life: 580, work: 90, mind: 1850 },
    recentActivity: { task: "30 min meditation",         category: "mind",    xp: 52,  minutesAgo: 75  },
    mainQuestToday: { task: "Silent breakfast",          category: "mind",    xp: 45,  status: "pending" },
    weeklyQuest:    { task: "Daily 30 min sit",          category: "mind",    xp: 290, daysLeft: 3, status: "pending" } },
  { id: "d4", name: "Nova",  username: "novabuilds",   initial: "N", totalXP: 7480, archetype: "artisan",  weeklyXP: 880, streak: 24,
    categoryXP: { fitness: 350, school: 850, life: 200, work: 5400, mind: 680 },
    recentActivity: { task: "Shipped client mockups",    category: "work",    xp: 156, minutesAgo: 22  },
    mainQuestToday: { task: "Review design system PR",   category: "work",    xp: 100, status: "complete" },
    weeklyQuest:    { task: "Ship v2 mockups",           category: "work",    xp: 440, daysLeft: 1, status: "pending" } },
  { id: "d5", name: "Soren", username: "sorencooks",   initial: "S", totalXP: 4290, archetype: "vitalist", weeklyXP: 510, streak: 11,
    categoryXP: { fitness: 720, school: 230, life: 2900, work: 160, mind: 280 },
    recentActivity: { task: "Cooked Sunday dinner",      category: "life",    xp: 48,  minutesAgo: 200 },
    mainQuestToday: { task: "Plan week's meals",         category: "life",    xp: 55,  status: "pending" },
    weeklyQuest:    { task: "Meal prep 5 dinners",       category: "life",    xp: 270, daysLeft: 5, status: "pending" } },
  { id: "d6", name: "Iris",  username: "irislifts",    initial: "I", totalXP: 6310, archetype: "warrior",  weeklyXP: 690, streak: 14,
    categoryXP: { fitness: 4800, school: 180, life: 600, work: 330, mind: 400 },
    recentActivity: { task: "Lifted PR · 2 plates",     category: "fitness", xp: 132, minutesAgo: 60  },
    mainQuestToday: { task: "Squats + deadlifts",       category: "fitness", xp: 130, status: "pending" },
    weeklyQuest:    { task: "Hit new PR squat",          category: "fitness", xp: 360, daysLeft: 4, status: "pending" } },
  { id: "d7", name: "Atlas", username: "atlasreads",   initial: "A", totalXP: 2840, archetype: "scholar",  weeklyXP: 350, streak: 3,
    categoryXP: { fitness: 190, school: 1900, life: 250, work: 330, mind: 170 },
    recentActivity: { task: "Read 40 pages",             category: "school",  xp: 68,  minutesAgo: 145 },
    mainQuestToday: { task: "Outline next essay",        category: "school",  xp: 80,  status: "pending" },
    weeklyQuest:    { task: "Finish 1 book",             category: "school",  xp: 320, daysLeft: 6, status: "pending" } },
  { id: "d8", name: "Wren",  username: "wrencodes",    initial: "W", totalXP: 5970, archetype: "artisan",  weeklyXP: 760, streak: 19,
    categoryXP: { fitness: 290, school: 740, life: 180, work: 4300, mind: 460 },
    recentActivity: { task: "Prototype shipped",         category: "work",    xp: 152, minutesAgo: 30  },
    mainQuestToday: { task: "Code review queue",         category: "work",    xp: 95,  status: "pending" },
    weeklyQuest:    { task: "Build prototype v3",        category: "work",    xp: 410, daysLeft: 3, status: "pending" } },
];

// ── Seed posts ──
// A handful of recent posts from friends so the Feed isn't empty on first run.
// Real posts get appended when the user completes a goal (see usePosts +
// useGameState). audienceCircleIds = [] means "visible to all my friends."
const _now = Date.now();
const _minsAgo = (m) => _now - m * 60 * 1000;
const _hoursAgo = (h) => _now - h * 60 * 60 * 1000;

export const SEED_POSTS = [
  {
    id: "p_seed_1",
    authorId: "f2",
    goalRef: { kind: "task", title: "Morning run · 5K", category: "fitness", xp: 102 },
    body: "",
    audienceCircleIds: [],
    audienceMode: "private",
    createdAt: _minsAgo(45),
    cheers: [{ userId: "f1", at: _minsAgo(40) }],
    comments: [],
  },
  {
    id: "p_seed_2",
    authorId: "f1",
    goalRef: { kind: "task", title: "Read 30 pages", category: "school", xp: 65 },
    body: "Finally finished chapter 4.",
    audienceCircleIds: [],
    audienceMode: "private",
    createdAt: _minsAgo(22),
    cheers: [],
    comments: [],
  },
  {
    id: "p_seed_3",
    authorId: "f3",
    goalRef: { kind: "task", title: "20 min meditation", category: "mind", xp: 38 },
    body: "",
    audienceCircleIds: [],
    audienceMode: "private",
    createdAt: _hoursAgo(3),
    cheers: [{ userId: "f4", at: _hoursAgo(2) }, { userId: "f5", at: _hoursAgo(2) }],
    comments: [],
  },
  {
    id: "p_seed_4",
    authorId: "f5",
    goalRef: { kind: "task", title: "Cooked a real dinner", category: "life", xp: 42 },
    body: "Tried that pasta recipe.",
    audienceCircleIds: [],
    audienceMode: "private",
    createdAt: _hoursAgo(1.5),
    cheers: [],
    comments: [],
  },
];

// Simulated phone contacts — some match Prominence users (`matchedUserId`),
// others are not on the app yet (matchedUserId: null → show "Invite" instead of "Add")
export const CONTACT_MATCHES = [
  { name: "Kai Tanaka",   phone: "+1 (555) 0142", matchedUserId: "d1" },
  { name: "Mira Patel",   phone: "+1 (555) 0287", matchedUserId: "d2" },
  { name: "Wren Cole",    phone: "+1 (555) 0319", matchedUserId: "d8" },
  { name: "Sam Reyes",    phone: "+1 (555) 0466", matchedUserId: null },
  { name: "Lou Park",     phone: "+1 (555) 0593", matchedUserId: null },
  { name: "Drew Bishop",  phone: "+1 (555) 0712", matchedUserId: null },
];
