export const SEED_FRIENDS = [
  { id: "f1", name: "Jordan",   initial: "J", totalXP: 4280, archetype: "scholar",  weeklyXP: 540, streak: 12,
    recentActivity: { task: "Read 30 pages",          category: "school",  xp: 65,  minutesAgo: 22  },
    mainQuestToday: { task: "Finish chapter outline", category: "school",  xp: 90,  status: "pending" },
    weeklyQuest:    { task: "Write 5,000 words",      category: "school",  xp: 320, daysLeft: 4, status: "pending" } },
  { id: "f2", name: "Sasha",    initial: "S", totalXP: 6720, archetype: "warrior",  weeklyXP: 820, streak: 22,
    recentActivity: { task: "Morning run · 5K",       category: "fitness", xp: 102, minutesAgo: 45  },
    mainQuestToday: { task: "Lift heavy + mobility",  category: "fitness", xp: 120, status: "complete" },
    weeklyQuest:    { task: "Run 25K total this week", category: "fitness", xp: 380, daysLeft: 2, status: "pending" } },
  { id: "f3", name: "Marcus",   initial: "M", totalXP: 2940, archetype: "monk",     weeklyXP: 380, streak: 4,
    recentActivity: { task: "20 min meditation",      category: "mind",    xp: 38,  minutesAgo: 180 },
    mainQuestToday: { task: "Journal morning pages",  category: "mind",    xp: 60,  status: "pending" },
    weeklyQuest:    { task: "Meditate 7 days straight", category: "mind",  xp: 280, daysLeft: 5, status: "pending" } },
  { id: "f4", name: "Riley",    initial: "R", totalXP: 5180, archetype: "artisan",  weeklyXP: 660, streak: 8,
    recentActivity: { task: "Shipped portfolio update", category: "work",  xp: 145, minutesAgo: 320 },
    mainQuestToday: { task: "Finish client deck",     category: "work",    xp: 130, status: "pending" },
    weeklyQuest:    { task: "Launch portfolio site",  category: "work",    xp: 420, daysLeft: 3, status: "pending" } },
  { id: "f5", name: "Ava",      initial: "A", totalXP: 3850, archetype: "vitalist", weeklyXP: 470, streak: 15,
    recentActivity: { task: "Cooked a real dinner",   category: "life",    xp: 42,  minutesAgo: 90  },
    mainQuestToday: { task: "Call mom + walk park",   category: "life",    xp: 75,  status: "pending" },
    weeklyQuest:    { task: "Cook 5 home meals",      category: "life",    xp: 260, daysLeft: 6, status: "pending" } },
];

export const DISCOVERABLE_USERS = [
  { id: "d1", name: "Kai",   initial: "K", totalXP: 8210, archetype: "warrior",  weeklyXP: 920, streak: 31,
    recentActivity: { task: "12K trail run",             category: "fitness", xp: 168, minutesAgo: 12  },
    mainQuestToday: { task: "Hill sprints",              category: "fitness", xp: 140, status: "pending" },
    weeklyQuest:    { task: "Run 50K this week",         category: "fitness", xp: 480, daysLeft: 2, status: "pending" } },
  { id: "d2", name: "Mira",  initial: "M", totalXP: 5640, archetype: "scholar",  weeklyXP: 720, streak: 18,
    recentActivity: { task: "Finished thesis chapter",   category: "school",  xp: 145, minutesAgo: 38  },
    mainQuestToday: { task: "Review committee notes",    category: "school",  xp: 110, status: "pending" },
    weeklyQuest:    { task: "Defend chapter draft",      category: "school",  xp: 400, daysLeft: 4, status: "pending" } },
  { id: "d3", name: "Theo",  initial: "T", totalXP: 3120, archetype: "monk",     weeklyXP: 410, streak: 6,
    recentActivity: { task: "30 min meditation",         category: "mind",    xp: 52,  minutesAgo: 75  },
    mainQuestToday: { task: "Silent breakfast",          category: "mind",    xp: 45,  status: "pending" },
    weeklyQuest:    { task: "Daily 30 min sit",          category: "mind",    xp: 290, daysLeft: 3, status: "pending" } },
  { id: "d4", name: "Nova",  initial: "N", totalXP: 7480, archetype: "artisan",  weeklyXP: 880, streak: 24,
    recentActivity: { task: "Shipped client mockups",    category: "work",    xp: 156, minutesAgo: 22  },
    mainQuestToday: { task: "Review design system PR",   category: "work",    xp: 100, status: "complete" },
    weeklyQuest:    { task: "Ship v2 mockups",           category: "work",    xp: 440, daysLeft: 1, status: "pending" } },
  { id: "d5", name: "Soren", initial: "S", totalXP: 4290, archetype: "vitalist", weeklyXP: 510, streak: 11,
    recentActivity: { task: "Cooked Sunday dinner",      category: "life",    xp: 48,  minutesAgo: 200 },
    mainQuestToday: { task: "Plan week's meals",         category: "life",    xp: 55,  status: "pending" },
    weeklyQuest:    { task: "Meal prep 5 dinners",       category: "life",    xp: 270, daysLeft: 5, status: "pending" } },
  { id: "d6", name: "Iris",  initial: "I", totalXP: 6310, archetype: "warrior",  weeklyXP: 690, streak: 14,
    recentActivity: { task: "Lifted PR · 2 plates",     category: "fitness", xp: 132, minutesAgo: 60  },
    mainQuestToday: { task: "Squats + deadlifts",       category: "fitness", xp: 130, status: "pending" },
    weeklyQuest:    { task: "Hit new PR squat",          category: "fitness", xp: 360, daysLeft: 4, status: "pending" } },
  { id: "d7", name: "Atlas", initial: "A", totalXP: 2840, archetype: "scholar",  weeklyXP: 350, streak: 3,
    recentActivity: { task: "Read 40 pages",             category: "school",  xp: 68,  minutesAgo: 145 },
    mainQuestToday: { task: "Outline next essay",        category: "school",  xp: 80,  status: "pending" },
    weeklyQuest:    { task: "Finish 1 book",             category: "school",  xp: 320, daysLeft: 6, status: "pending" } },
  { id: "d8", name: "Wren",  initial: "W", totalXP: 5970, archetype: "artisan",  weeklyXP: 760, streak: 19,
    recentActivity: { task: "Prototype shipped",         category: "work",    xp: 152, minutesAgo: 30  },
    mainQuestToday: { task: "Code review queue",         category: "work",    xp: 95,  status: "pending" },
    weeklyQuest:    { task: "Build prototype v3",        category: "work",    xp: 410, daysLeft: 3, status: "pending" } },
];
